"use strict";
exports.__esModule = true;
var name = "Fahmi irsyad khairi";
var age = 18;
var role = "Mahasiswa";
var isMarried = false;
var year = 2018;
console.log({ name: name }, { age: age }, { role: role }, { isMarried: isMarried }, { year: year });
var n = null;
var u = undefined;
var isPunyaPacar = null;
var isPunyaGebetan = undefined;
var mix = 8;
mix = true;
mix = "Its mixed";
console.log(mix.toUpperCase());
var mixUnkown = "hello";
mixUnkown = false;
mixUnkown = "its unkown";
console.log(mixUnkown.toUpperCase());
var list1 = [1, 2, 3];
var list2 = [1, 2, 3];
var list3 = ["saya", "dia", "kita"];
var list4 = ["saya", "dia", "kita"];
console.log(list1, list2, list3, list4, mix);
var person1 = ["fahmi irsyad", 18];
var color;
(function (color) {
    color[color["red"] = 5] = "red";
    color[color["green"] = 6] = "green";
    color[color["blue"] = 7] = "blue";
})(color || (color = {}));
;
var c = color.green;
console.log(c);
