// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var cubic = 15;

var b = "hello";

console.log(b);

console.log(cubic);

console.log(true);

var greet = "Greet ReasonML";

var a = 5;

exports.greet = greet;
exports.b = b;
exports.cubic = cubic;
exports.a = a;
/*  Not a pure module */
