// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var $$final = "Hello, ReasonML";

console.log($$final);

var greet = true;

exports.greet = greet;
/*  Not a pure module */
